spring:
  messages:
    basename: i18n.login
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  profiles:
    active: dev

# comment.avatar: /images/avatar.jpg
