spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: 0516
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  messages:
    basename: i18n.login
server:
  servlet:
    context-path: /crud-pro

